config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :omniauth_registrations, only: [:new, :create]

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :withdraw_vote
    end
  end
  
  resources :questions, concerns: :votable do
    resources :subscribers, only: [:create]
    resources :answers, except: [:index, :show, :edit], shallow: true, concerns: :votable do
      patch :best, on: :member
    end
  end

  resources :questions do
    resources :comments, defaults: { commentable: 'question' }
  end

  resources :answers do
    resources :comments, defaults: { commentable: 'answer' }
  end

  resources :attachments, only: [:destroy]
  resources :subscribers, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true 
      end
    end
  end

  resources :searches
  
  root to: "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Commentable

  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable
  has_many :votes, as: :votable
  has_many :subscribers

  validates :title, :body, :user,  presence: true
  
  #  accepts_nested_attributes_for :attachments
  accepts_nested_attributes_for :attachments, reject_if: proc { |attrib| attrib['file'].nil? }

  after_save :update_reputation

  private

  def update_reputation
    self.delay.calculate_reputation
  end
  
  def calculate_reputation
    reputation = Reputation.calculate(self)
    self.user.update(reputation: reputation)
  end

end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def create
    @question = Question.create question_params.merge(user_id: current_resource_owner.id)
    respond_with @question
  end

  private

  def question_params
    strong_params = params.require(:question).permit(:title, :body)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :user_created_question?, only: [:update, :destroy]
  before_action :build_answer, only: [:show]
  respond_to :html

 authorize_resource
  
  include Voted
  
  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end
  
  def create
    @question = Question.new(question_params)
    @question.user = current_user
    @question.save
    respond_with(@question)
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    respond_with(@question.destroy!)
  end

  private

  def build_answer
    @answer = @question.answers.build
  end
  
  def load_question
    @question = Question.find(params[:id])
  end

  def user_created_question?
    if @question.user_id != current_user.id
      redirect_to @question, notice: 'Question can be modified/deleted strictly by its author only'
    end
  end
  
  def question_params
    strong_params = params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
- cache question do
  div id="question_#{question.id}"

    td.question_votes
      = render 'layouts/votes/show', votable: question

    p= question.title
    p= question.body

    .question-container
      p Attachments:

      - question.attachments.each do |a|
        div class="filename" id="file_#{a.id}"
          = link_to a.file.identifier, a.file.url
          - if current_user.present? && current_user.id == question.user_id
            = link_to 'Delete Attachment', a, method: :delete, id: "delete_file_#{ a.id }", remote: true

    - if current_user.present? && current_user.id == question.user_id
      p= link_to "Delete Question", question, method: :delete


    - if user_signed_in?
      .comments_new
        span =< link_to "Create question comment", '', id: "link_new_comment_for_#{ dom_id question }", class: "link_new_comment", data: { question: dom_id(question) }

        = form_for [question, question.comments.new], remote: true, html: { id: "form_new_comment_for_#{ dom_id question}", style: "display: true" } do |f|
          p
            = f.label :body, t("comment.label.body")
            br
            = f.text_area :body

          p = f.submit "Submit"

    = div_for question, :comments, class: :comments
      = render question.comments

app/views/questions/index.html.slim
= render :partial =>  'searches/form'
- cache collection_cache_key_for :question do
  - @questions.each do |question|
    p= link_to question.title, question

    - if current_user.present? && current_user.id == question.user_id
      p= link_to "Delete Question", question, method: :delete

  - if can?(:create, Question)
    p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= nested_form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = a.label :file
      = a.file_field :file   
      = a.link_to_remove "Delete File"
    p = f.link_to_add "Add file to question", :attachments
    = f.submit 'Create'

app/views/questions/show.html.slim
= render @question
h3 Answers:
.answers
  = render @question.answers

- if current_user.present?
  = render 'answers/new', question: @question

= subscribe_to "/questions/#{@question.id}"