config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :omniauth_registrations, only: [:new, :create]

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :withdraw_vote
    end
  end
  
  resources :questions, concerns: :votable do
    resources :subscribers, only: [:create]
    resources :answers, except: [:index, :show, :edit], shallow: true, concerns: :votable do
      patch :best, on: :member
    end
  end

  resources :questions do
    resources :comments, defaults: { commentable: 'question' }
  end

  resources :answers do
    resources :comments, defaults: { commentable: 'answer' }
  end

  resources :attachments, only: [:destroy]
  resources :subscribers, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true 
      end
    end
  end

  resources :searches
  
  root to: "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  include Commentable
  
  belongs_to :question, touch: true
  belongs_to :user

  has_many :attachments, as: :attachable
#  has_many :votes, as: :votable
  
  validates :body, presence: true

  # accepts_nested_attributes_for :attachments
  accepts_nested_attributes_for :attachments, reject_if: proc { |attrib| attrib['file'].nil? }
  
  default_scope { order(best: :desc, created_at: :asc) }

  after_create :calculate_rating

  def make_best
    self.question.answers.update_all(best: false)
    self.update(best: true)
  end

  private

  def calculate_rating
    Reputation.delay.calculate(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_answer, only: [ :edit, :update, :destroy, :best ]
  before_action :load_question, only: [ :create, :update ]
  before_action :user_created_answer?, only: [ :update, :destroy ]
  before_action :user_created_question?, only: [:best]

  respond_to :html
  respond_to :js

 authorize_resource
  
  include Voted
  
  def new
    respond_with(@answer = @question.answers.new)
  end

  def edit
  end

  def create
    @answer = @question.answers.create(answer_params)
    @answer.user = current_user
    respond_with(@answer)
  end

  def update
    respond_with @answer
  end

  def best
    @answers = @answer.question.answers
    @answer.make_best
  end
  
  def destroy
    respond_with(@answer.destroy)
  end

  private

  def load_question
    @question = params.has_key?(:question_id) ? Question.find(params[:question_id]) : @answer.question
  end
  
  def load_answer
    @answer = Answer.find(params[:id])
  end

  def user_created_answer?
    if @answer.user_id != current_user.id
      redirect_to @question, notice: 'Answer can be modified/deleted strictly by its author only'
    end
  end

  def user_created_question?
    unless @answer.question.user_id == current_user.id
      render status: 403, text: "Only author of question can mark best answer"
    end
  end
  
  def answer_params
    strong_params = params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, except: :show

  authorize_resource
  
  def index
    respond_with (@answers = @question.answers)
  end

  def show
    respond_with Answer.find(params[:id])
  end
  
  def create
    @answer = @question.answers.create answer_params.merge(user_id: current_resource_owner.id)
    respond_with @answer
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    strong_params = params.require(:answer).permit(:body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  - cache answer do
    = div_for answer

      td.answer_votes
        = render 'layouts/votes/show', votable: answer

      p = answer.body 

      ul
        - answer.attachments.each do |a|
          div class="filename" id="file_#{a.id}"
            = link_to a.file.identifier, a.file.url
            - if current_user.present? && current_user.id == @question.user_id
              = link_to 'Delete Attachment', a, method: :delete, id: "delete_file_#{ a.id }", remote: true

      - if answer.best?
        p = 'The best answer!'
      - else
        - question = answer.question
        - if current_user == question.user
          = link_to "Best", best_answer_path(answer), method: :patch, remote: true
          span =>
      - if user_signed_in? && current_user.id == answer.user_id
        = render 'shared/link_edit', item: answer
        =< render 'shared/link_delete', item: answer

        p 
          = form_for answer, remote: true, html: { id: "for_answer_edit_#{ answer.id }" } do |f|
            = f.label :body, "Answer"
            = f.text_area :body
            = f.submit 'Saves'

      = div_for answer, :comments, class: :comments
        = render answer.comments

      - if user_signed_in?
        .comments_new

          span =< link_to "Create comment", '', id: "link_new_comment_for_#{ dom_id answer }", class: "link_new_comment", data: { answer: dom_id(answer) }

          = form_for [answer, answer.comments.new], remote: true, html: { id: "form_new_comment_for_#{ dom_id answer}", style: "display: true" } do |f|
            p
              = f.label :body, t("comment.label.body")
              br
              = f.text_area :body
              / = hidden_field_tag(:commentable_class, "Answer")
              / = hidden_field_tag(:commentable_id, answer.id)

            p = f.submit "Submit"

app/views/answers/_new.html.slim
= nested_form_for [question, @answer], remote: true do |f|
  p
    = f.label     :body, 'Your answer'
    .answer-errors
    = f.text_area :body
  p
    = f.fields_for :attachments, @answer.attachments.build do |a|
      = a.label :file
      = a.file_field :file
      = a.link_to_remove 'Remove File'
    p = f.link_to_add 'Add more files', :attachments
    = f.submit 'Create Answer'

app/views/answers/best.js.erb
$('.answers').html('<%= j render @answers %>');

app/views/answers/create.html.slim
h1 Answers#create
p Find me in app/views/answers/create.html.slim

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  <% publish_to "/questions/#{ @answer.question.id }" do %>
	$('.answers').append('<%= j render @answer %>');
  <% end %>
  $('textarea#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<%= render 'shared/remove_item_after_destroy', item: @answer, channel: "/questions/#{ @answer.question.id }" %>

app/views/answers/edit.html.slim
h1 Answers#edit
p Find me in app/views/answers/edit.html.slim

app/views/answers/index.html.slim
h1 = @question.title
h1 = @question.id
p= @question.body
p Answers:
- @question.answers.each do |answer|
  p
    = answer.body
    |, 
    - if current_user.present? and current_user.id == answer.user_id
    = link_to "Delete Answer", question_answer_path(@question, answer.id), method: :delete 

- if current_user.present? 
  p= link_to "Create Answer", new_question_answer_path(@question)

- if current_user.present? and current_user.id == @question.user_id
  p= link_to "Delete Question", @question, method: :delete 
h1 Answers#index
p Find me in app/views/answers/index.html.slim

app/views/answers/new.html.slim
= form_for [@question, @answer], remote: true do |f|
  = f.label     :body, 'body'
  = f.text_area :body
  = f.submit

app/views/answers/show.html.slim
p= @question.title
p= @question.body

p Answers:
- @question.answers.each do |answer|
  p= answer.body

  - if current_user.present? and current_user.id == answer.user_id
    p= link_to "Delete Answer", question_answer_path(@question, answer.id), method: :delete 

- if current_user.present? 
  p= link_to "Create Answer", new_question_answer_path(@question)

- if current_user.present? and current_user.id == @question.user_id
  p= link_to "Delete Question", @question, method: :delete 

app/views/answers/update.html.slim
h1 Answers#update
p Find me in app/views/answers/update.html.slim

app/views/answers/update.js.erb
$('#answer_<%= @answer.id %>').replaceWith('<%= j render @answer %>');