config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :omniauth_registrations, only: [:new, :create]

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :withdraw_vote
    end
  end
  
  resources :questions, concerns: :votable do
    resources :subscribers, only: [:create]
    resources :answers, except: [:index, :show, :edit], shallow: true, concerns: :votable do
      patch :best, on: :member
    end
  end

  resources :questions do
    resources :comments, defaults: { commentable: 'question' }
  end

  resources :answers do
    resources :comments, defaults: { commentable: 'answer' }
  end

  resources :attachments, only: [:destroy]
  resources :subscribers, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true 
      end
    end
  end

  resources :searches
  
  root to: "questions#index"

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def index
    searchable = params[:conditions].to_s
    if %w(Question Answer Comment User All).include? searchable
      if searchable == "All"
        searchable = "ThinkingSphinx"
      end
      @search = searchable.classify.constantize.search params[:search]
    end
    authorize! :index, @search
  end

end

app/views/searches/_answer.html.slim
p= s.body

app/views/searches/_comment.html.slim
p= s.body

app/views/searches/_form.html.slim
= form_tag(searches_path, method: "get") do
  = label_tag(:search, "Search for:")
  = select_tag "conditions", options_for_select(["Question", "Answer", "Comment", "User" ,"All"])
  = text_field_tag :search, params[:search]
  = submit_tag "Search"

app/views/searches/_question.html.slim
p= s.title
p= s.body
hr

app/views/searches/_user.html.slim
p= s.email

app/views/searches/index.html.slim
- if @search
	- @search.each do |s|
	  = render partial: "#{s.class.name.downcase}", object: s, as: 's'