config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :omniauth_registrations, only: [:new, :create]

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :withdraw_vote
    end
  end
  
  resources :questions, concerns: :votable do
    resources :subscribers, only: [:create]
    resources :answers, except: [:index, :show, :edit], shallow: true, concerns: :votable do
      patch :best, on: :member
    end
  end

  resources :questions do
    resources :comments, defaults: { commentable: 'question' }
  end

  resources :answers do
    resources :comments, defaults: { commentable: 'answer' }
  end

  resources :attachments, only: [:destroy]
  resources :subscribers, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true 
      end
    end
  end

  resources :searches
  
  root to: "questions#index"

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :user_id, uniqueness: { scope: :question_id }


  scope :to_questions_digest_not_sent_after, ->(date) { where(question_id: nil).
         where("coalesce(sent_at, '1970-01-01') < :date", date: date)  }
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
 before_action :authenticate_user!
  before_action :load_question, only: :create
  before_action :load_subscriber, only: :destroy

  respond_to :js

  authorize_resource

  def create
    # binding.pry
    respond_with(@subscriber = @question.subscribers.create(user: current_user))
  end

  def destroy
    respond_with(@subscriber.destroy)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_subscriber
    @subscriber = Subscriber.find(params[:id])
  end

end

app/views/subscribers/_subscriber.html.slim
- if user_signed_in?
  - if can?(:create, Subscriber.new(question: question))
    =link_to 'Subscribe to the question', question_subscribers_path(question), method: :post, remote: true
  - elsif current_user.subscribed_to?(question)
    -if can?(:destroy, current_user.subscription_to(question))
    =link_to 'Unsubscribe from the question', subscriber_path(current_user.subscription_to(question) ), method: :delete, remote: true

app/views/subscribers/create.js.erb
$('.subscriber').replaceWith('<%= j render :partial =>  'subscriber', locals: {question: @subscriber.question} %>')